language: go

go:
  - "1.13"

before_install:
 - go get github.com/mitchellh/gox

install:
 - go get -t -v ./...

script:
 - go vet $(go list ./... | grep -v /vendor/)
 - go test -v ./...
 - gox -os="linux darwin windows" -arch="amd64" -output="out/rare.." -verbose ./...
